INSERT INTO books (isbn, title, author, first_publish_year, section, shelf, state)
VALUES
                                                                                       ('9780261103252', 'The Lord of the Rings', 'J.R.R. Tolkien', 1954, 'Fantasy', 'A1', 'In stock'),
                                                                                       ('9780618640157', 'The Two Towers', 'J.R.R. Tolkien', 1954, 'Fantasy', 'A1', 'In stock'),
                                                                                       ('9780007123819', 'The Fellowship of the Ring', 'J.R.R. Tolkien', 1954, 'Fantasy', 'A1', 'Loaned'),
                                                                                       ('9780007123826', 'The Return of the King', 'J.R.R. Tolkien', 1955, 'Fantasy', 'A1', 'In stock'),
                                                                                       ('9780618260262', 'The Hobbit', 'J.R.R. Tolkien', 1937, 'Fantasy', 'B1', 'In stock'),
                                                                                       ('9780007488351', 'The Silmarillion', 'J.R.R. Tolkien', 1977, 'Fantasy', 'B2', 'In stock'),
                                                                                       ('9780345339737', 'The Fellowship of the Ring', 'J.R.R. Tolkien', 1954, 'Fantasy', 'A1', 'In stock'),
                                                                                       ('9780547952017', 'The Hobbit and The Lord of the Rings', 'J.R.R. Tolkien', 2012, 'Fantasy', 'B1', 'In stock'),
                                                                                       ('9780618517657', 'The Children of Húrin', 'J.R.R. Tolkien', 2007, 'Fantasy', 'B2', 'In stock'),
                                                                                       ('9780007355141', 'Unfinished Tales', 'J.R.R. Tolkien', 1980, 'Fantasy', 'B2', 'Loaned'),
                                                                                       ('9780395071229', 'Novels (Hobbit / Lord of the Rings)', 'J.R.R. Tolkien', 1979, 'Collection', 'C1', 'In stock'),
                                                                                       ('9780451126548', 'Bored of the Rings', 'Harvard Lampoon', 1969, 'Parody', 'D1', 'In stock'),
                                                                                       ('9780618154026', 'The lord of the rings', 'Brian Sibley', 2001, 'Film', 'D2', 'In stock'),
                                                                                       ('9780395515624', 'The War of the Ring', 'J.R.R. Tolkien', 1990, 'Fantasy', 'A3', 'In stock'),
                                                                                       ('9780261102248', 'The Return of the Shadow', 'J.R.R. Tolkien', 1988, 'Fantasy', 'B3', 'In stock'),                                                                                       ('9780439554930', 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 1997, 'Fantasy', 'F1', 'Loaned'),
                                                                                       ('9780439064873', 'Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 1998, 'Fantasy', 'F1', 'In stock'),
                                                                                       ('9780439136365', 'Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 1999, 'Fantasy', 'F1', 'In stock'),
                                                                                       ('9780140283334', '1984', 'George Orwell', 1949, 'Dystopian', 'G1', 'Loaned'),
                                                                                       ('9780142437261', 'Animal Farm', 'George Orwell', 1945, 'Dystopian', 'G1', 'In stock'),
                                                                                       ('9780743273565', 'The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'Classic', 'H1', 'In stock'),
                                                                                       ('9780142437230', 'To Kill a Mockingbird', 'Harper Lee', 1960, 'Classic', 'H2', 'In stock'),
                                                                                       ('9780316769488', 'The Catcher in the Rye', 'J.D. Salinger', 1951, 'Classic', 'H3', 'Loaned'),
                                                                                       ('9780134685991', 'Effective Java', 'Joshua Bloch', 2018, 'Technology', 'I1', 'In stock'),
                                                                                       ('9780596007126', 'Head First Design Patterns', 'Eric Freeman', 2004, 'Technology', 'I2', 'In stock'),
                                                                                       ('9780321125217', 'Domain-Driven Design', 'Eric Evans', 2003, 'Technology', 'I3', 'Loaned'),
                                                                                       ('9781501127625', 'Steve Jobs', 'Walter Isaacson', 2011, 'Biography', 'J1', 'In stock'),
                                                                                       ('9781501135927', 'Elon Musk', 'Ashlee Vance', 2015, 'Biography', 'J1', 'In stock'),
                                                                                       ('9780679768178', 'Guns, Germs, and Steel', 'Jared Diamond', 1997, 'History', 'K1', 'In stock'),
                                                                                       ('9780060935467', 'Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 2011, 'History', 'K1', 'Loaned');